apiVersion: v1
kind: Service
metadata:
  name: tone-analyzer-nodejs-service
spec:
  type: NodePort
  ports:
  - name: http
    port: 3000
  selector:
    app: tone-analyzer-nodejs-selector
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tone-analyzer-nodejs-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: tone-analyzer-nodejs-selector
    spec:
      containers:
      - name: tone-analyzer-nodejs
        image: ibmwatson/tone-analyzer-nodejs:latest
        ports:
          - name: http
            containerPort: 3000
            protocol: TCP
        readinessProbe:
          httpGet:
            path: /healthcheck
        livenessProbe:
          httpGet:
            path: /healthcheck
